let productos = [
  {
    id: 1,
    nombre: "Auricular Bluetooth Apple AirPods Max",
    tipo: "Auriculares Bluetooth",
    cantidad: 1,
    precio: 211120,
    oferta: true,
    img: "../assets/images/auriculares/air-max.jpg",
  },
  {
    id: 2,
    nombre: "Auricular Bluetooth Lenovo LP75 Sport TWS Black",
    tipo: "Auriculares Bluetooth",
    cantidad: 1,
    precio: 12922,
    oferta: false,
    img: "../assets/images/auriculares/lenovolp75.jpg",
  },
  {
    id: 3,
    nombre: "Auriculares Bluetooth Sony WF-C500 White",
    tipo: "Auriculares Bluetooth",
    cantidad: 1,
    precio: 21658,
    oferta: false,
    img: "../assets/images/auriculares/sony-wf.jpg",
  },
  {
    id: 4,
    nombre: "Auricular Bluetooth Anker Soundcore Life Q30 Pink",
    tipo: "Auriculares Bluetooth",
    cantidad: 1,
    precio: 47320,
    oferta: false,
    img: "../assets/images/auriculares/anker-soundcore.jpg",
  },
  {
    id: 5,
    nombre: "Auricular In Ear Jbl C50HI Negro",
    tipo: "Auriculares Con Cable",
    cantidad: 1,
    precio: 3185,
    oferta: false,
    img: "../assets/images/auriculares/jblc50.jpg",
  },
  {
    id: 6,
    nombre: "Auricular Sony MDR-ZX310AP",
    tipo: "Auriculares Con Cable",
    cantidad: 1,
    precio: 5851,
    oferta: false,
    img: "../assets/images/auriculares/sonycable.jpg",
  },
  {
    id: 7,
    nombre: "Auriculares Sony EX15 AP",
    tipo: "Auriculares Con Cable",
    cantidad: 1,
    precio: 2912,
    oferta: false,
    img: "../assets/images/auriculares/sonycable2.jpg",
  },
  {
    id: 8,
    nombre: "Auriculares Inalambricos Sony MDR-IF245RK para TV",
    tipo: "Auriculares Inalambricos",
    cantidad: 1,
    precio: 32760,
    oferta: false,
    img: "../assets/images/auriculares/sonyprof.jpg",
  },
  {
    id: 9,
    nombre: "Auriculares Inalambricos Sony MDR-IF985RK",
    tipo: "Auriculares Inalambricos",
    cantidad: 1,
    precio: 22386,
    oferta: false,
    img: "../assets/images/auriculares/sonyprof2.jpg",
  },
  {
    id: 10,
    nombre: "Barra de sonido Sony HT-S40R 5.1ch",
    tipo: "Barra De Sonido",
    cantidad: 1,
    precio: 194740,
    oferta: false,
    img: "../assets/images/auriculares/barra1.jpg",
  },
  {
    id: 11,
    nombre: "Barra de sonido Sony HT-S400 2.1ch ( Barra + Subwoofer)",
    tipo: "Barra De Sonido",
    cantidad: 1,
    precio: 119210,
    oferta: false,
    img: "../assets/images/auriculares/barra3.jpg",
  },
  {
    id: 12,
    nombre: "Barra de Sonido Redragon Gs570 Darknet Iluminación Rgb",
    tipo: "Barra De Sonido",
    cantidad: 1,
    precio: 10992,
    oferta: true,
    img: "../assets/images/auriculares/barra2.jpg",
  },
  {
    id: 13,
    nombre: "Auricular Bluetooth Edifier W820NB Grey HI-RES Audio Noise Cancelling",
    tipo: "Auriculares Inalambricos",
    cantidad: 1,
    precio: 38220,
    oferta: false,
    img: "../assets/images/auriculares/edifierw82.jpg",
  },
  {
    id: 14,
    nombre: "Auricular Bluetooth Xiaomi Redmi Buds 4 Touch",
    tipo: "Auriculares Inalambricos",
    cantidad: 1,
    precio: 28210,
    oferta: false,
    img: "../assets/images/auriculares/redmi1.jpg",
  },
  {
    id: 15,
    nombre: "Auricular Bluetooth Apple AirPods Pro 2",
    tipo: "Auriculares Inalambricos",
    cantidad: 1,
    precio: 114114,
    oferta: true,
    img: "../assets/images/auriculares/AirPods.jpg",
  },
  {
    id: 16,
    nombre: "Auricular Jbl Endurance Run Bluetooth Black/Yellow",
    tipo: "Auriculares Inalambricos",
    cantidad: 1,
    precio: 10010,
    oferta: false,
    img: "../assets/images/auriculares/jblauris.jpg",
  },
];
